### ISSUE TITLE
Items in queue wrong .

### ISSUE THREAD

**Issue by paneaktae** [delannoyk/AudioPlayer#103]
When i add items to queue two items , but i call previous or next two times player can changed item.

**Comment by paneaktae** [comment]
i mean to previous function wrong

**Comment by delannoyk** [comment]
Fixed on master.
Thanks for reporting this.

**Comment by paneaktae** [comment]
thx for support :)

**Comment by jadsonlourenco** [comment]
Send a new release?

**Comment by delannoyk** [comment]
Done! 1.1.0 is up

**Comment by Smiacter** [comment]
There is still a problem, previous function is wrong, hasPrevious is wrong...

**Comment by jadsonlourenco** [comment]
Yes, I can confirm, the issue is "open" again.

**Comment by qky1412** [comment]
I met same problem when it comes to 2 items in queue, is there a work around?

**Comment by zyvv** [comment]
when it comes to one item in queue, hasPrevious is wrong

**Comment by delannoyk** [comment]
Reopened the issue. I'm happy to review a PR if anyone is down to contribute otherwise I'll try to fix it soon.

**Comment by zyvv** [comment]
```
    var hasPreviousItem: Bool {
        if !queue.isEmpty &&
            (nextPosition - 1 > 0 || mode.contains(.repeat) || mode.contains(.repeatAll)) {
            return true
        }
        return false
    }
```
maybe should this.
