### ISSUE TITLE
Inconsistent buffering state

### ISSUE THREAD

**Issue by funkenstrahlen** [delannoyk/AudioPlayer#16]
When I call the player to play an item for the first time after initialization it does not go into buffering state. It directly moves into `playing` state.

```swift
let player = AudioPlayer()
let item = AudioItem(mediumQualitySoundURL: event.streamurl)
player.playItem(item)
```

It does not change its state until the item is actually playing. No buffering state before.

When the player has been in `playing` state for one time and I set a new item to play it always does *buffering* -> *playing* or simply stays in *buffering* if no content was found.

**Comment by funkenstrahlen** [comment]
I just realised what is the problem. When I start the player for the first time `func audioPlayer(audioPlayer: AudioPlayer, didChangeStateFrom from: AudioPlayerState, toState to: AudioPlayerState)` is called with the info **buffering** -> **playing**.

So **buffering** is the init state of the player? I exptected `didChangeStateFrom` also to be called when I play a new item and the player starts buffering.

**Comment by delannoyk** [comment]
Yup, that wasn't intended and I agree the initial state should be `.Stopped`!
Also solved in [develop](https://github.com/delannoyk/AudioPlayer/tree/develop)

**Comment by funkenstrahlen** [comment]
I commented on your commit, because I think there is still a problem.

**Comment by delannoyk** [comment]
Yeah I saw that, sorry about that, was a long day yesterday. Fixing it now.

**Comment by funkenstrahlen** [comment]
No hurry :)

I just was not sure if Github sends notifications for commit comments too.
