### ISSUE TITLE
Notification center progress bar doesn't stop

### ISSUE THREAD

**Issue by Jauzee** [delannoyk/AudioPlayer#33]
Thank you for the lot of work you did. Player is nice. But I have one issue:

Audio player continues to update notification center progress bar even if pause() is called.

**Comment by delannoyk** [comment]
You're right.
Fixed it in `develop`, will release it later.

**Comment by Jauzee** [comment]
I've checked with those changes, but they doesn't fix the issue. )

**Comment by delannoyk** [comment]
Whoopsie, you're right, last commit wasn't pushed.
